"""schema inicial

Revision ID: c0a071374ade
Revises: 
Create Date: 2026-07-17 15:54:30.152665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a071374ade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('fuel_cost_type',
    sa.Column('cost_name', sa.String(length=120), nullable=False),
    sa.Column('cost_type', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_cost_type_legacy_id'), 'fuel_cost_type', ['legacy_id'], unique=True)
    op.create_table('maintenance_classification',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_classification_legacy_id'), 'maintenance_classification', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_maintenance_classification_name'), 'maintenance_classification', ['name'], unique=True)
    op.create_table('maintenance_cost_type',
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('cost_group', sa.String(length=120), nullable=False),
    sa.Column('cost_type', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_cost_type_legacy_id'), 'maintenance_cost_type', ['legacy_id'], unique=True)
    op.create_table('operational_cost',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_cost_legacy_id'), 'operational_cost', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_operational_cost_name'), 'operational_cost', ['name'], unique=True)
    op.create_table('vehicle_category',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_category_legacy_id'), 'vehicle_category', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_vehicle_category_name'), 'vehicle_category', ['name'], unique=True)
    op.create_table('vehicle',
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('chassis', sa.String(length=60), nullable=True),
    sa.Column('renavan', sa.String(length=60), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('tracker', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vehicle_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_category_id'), 'vehicle', ['category_id'], unique=False)
    op.create_index(op.f('ix_vehicle_legacy_id'), 'vehicle', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_vehicle_plate'), 'vehicle', ['plate'], unique=True)
    op.create_table('fuel_record',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('fuel_cost_type_id', sa.Uuid(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('category_name', sa.String(length=120), nullable=True),
    sa.Column('cost_name', sa.String(length=120), nullable=False),
    sa.Column('cost_type', sa.String(length=120), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=4), nullable=False),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fuel_cost_type_id'], ['fuel_cost_type.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_record_date'), 'fuel_record', ['date'], unique=False)
    op.create_index(op.f('ix_fuel_record_fuel_cost_type_id'), 'fuel_record', ['fuel_cost_type_id'], unique=False)
    op.create_index(op.f('ix_fuel_record_legacy_id'), 'fuel_record', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_fuel_record_plate'), 'fuel_record', ['plate'], unique=False)
    op.create_index(op.f('ix_fuel_record_vehicle_id'), 'fuel_record', ['vehicle_id'], unique=False)
    op.create_table('maintenance_record',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('classification_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_cost_type_id', sa.Uuid(), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('category_name', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('cost_group', sa.String(length=120), nullable=False),
    sa.Column('cost_type', sa.String(length=120), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['maintenance_classification.id'], ),
    sa.ForeignKeyConstraint(['maintenance_cost_type_id'], ['maintenance_cost_type.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_classification_id'), 'maintenance_record', ['classification_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_date'), 'maintenance_record', ['date'], unique=False)
    op.create_index(op.f('ix_maintenance_record_legacy_id'), 'maintenance_record', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_maintenance_record_maintenance_cost_type_id'), 'maintenance_record', ['maintenance_cost_type_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_plate'), 'maintenance_record', ['plate'], unique=False)
    op.create_index(op.f('ix_maintenance_record_vehicle_id'), 'maintenance_record', ['vehicle_id'], unique=False)
    op.create_table('operational_cost_record',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('operational_cost_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('cost_name', sa.String(length=120), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_model', sa.String(length=255), nullable=True),
    sa.Column('category_name', sa.String(length=120), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=True),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('observation', sa.String(), nullable=True),
    sa.Column('legacy_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operational_cost_id'], ['operational_cost.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_cost_record_date'), 'operational_cost_record', ['date'], unique=False)
    op.create_index(op.f('ix_operational_cost_record_legacy_id'), 'operational_cost_record', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_operational_cost_record_operational_cost_id'), 'operational_cost_record', ['operational_cost_id'], unique=False)
    op.create_index(op.f('ix_operational_cost_record_plate'), 'operational_cost_record', ['plate'], unique=False)
    op.create_index(op.f('ix_operational_cost_record_vehicle_id'), 'operational_cost_record', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operational_cost_record_vehicle_id'), table_name='operational_cost_record')
    op.drop_index(op.f('ix_operational_cost_record_plate'), table_name='operational_cost_record')
    op.drop_index(op.f('ix_operational_cost_record_operational_cost_id'), table_name='operational_cost_record')
    op.drop_index(op.f('ix_operational_cost_record_legacy_id'), table_name='operational_cost_record')
    op.drop_index(op.f('ix_operational_cost_record_date'), table_name='operational_cost_record')
    op.drop_table('operational_cost_record')
    op.drop_index(op.f('ix_maintenance_record_vehicle_id'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_plate'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_maintenance_cost_type_id'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_legacy_id'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_date'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_classification_id'), table_name='maintenance_record')
    op.drop_table('maintenance_record')
    op.drop_index(op.f('ix_fuel_record_vehicle_id'), table_name='fuel_record')
    op.drop_index(op.f('ix_fuel_record_plate'), table_name='fuel_record')
    op.drop_index(op.f('ix_fuel_record_legacy_id'), table_name='fuel_record')
    op.drop_index(op.f('ix_fuel_record_fuel_cost_type_id'), table_name='fuel_record')
    op.drop_index(op.f('ix_fuel_record_date'), table_name='fuel_record')
    op.drop_table('fuel_record')
    op.drop_index(op.f('ix_vehicle_plate'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_legacy_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_category_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_vehicle_category_name'), table_name='vehicle_category')
    op.drop_index(op.f('ix_vehicle_category_legacy_id'), table_name='vehicle_category')
    op.drop_table('vehicle_category')
    op.drop_index(op.f('ix_operational_cost_name'), table_name='operational_cost')
    op.drop_index(op.f('ix_operational_cost_legacy_id'), table_name='operational_cost')
    op.drop_table('operational_cost')
    op.drop_index(op.f('ix_maintenance_cost_type_legacy_id'), table_name='maintenance_cost_type')
    op.drop_table('maintenance_cost_type')
    op.drop_index(op.f('ix_maintenance_classification_name'), table_name='maintenance_classification')
    op.drop_index(op.f('ix_maintenance_classification_legacy_id'), table_name='maintenance_classification')
    op.drop_table('maintenance_classification')
    op.drop_index(op.f('ix_fuel_cost_type_legacy_id'), table_name='fuel_cost_type')
    op.drop_table('fuel_cost_type')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
